projects:
  - name: Test B
    url: https://github.com/TechnicalDevOp/TestFactory2.git
    tests_covered:
      - Integration Tests
  - name: Test A
    url: https://github.com/TechnicalDevOp/TestFactory2.git
    tests_covered:
      - Unit Tests
      - Smoke Tests
    
