projects:
  - test_name: Test C
    git_url: https://github.com/TechnicalDevOp/testFactory3.git
    tests_covered:
      - Pump Tests
    dependencies:
      - name: Pump Service
  - test_name: Test B
    git_url: https://github.com/TechnicalDevOp/TestFactory2.git
    tests_covered:
      - Integration Tests
  - test_name: Test A
    git_url: https://github.com/TechnicalDevOp/TestFactory2.git
    tests_covered:
      - Unit Tests
      - Smoke Tests
services:
  - name: Pump Service
    git_url: https://github.com/TechnicalDevOp/testService.git
config:
  - id: test-b-001
